os:
  - linux
language: c
compiler:
  - gcc
  - clang
env:
  matrix:
    - FEATURES=tiny
    - FEATURES=small
    - FEATURES=normal
    - FEATURES=big
    - FEATURES=huge
branches:
  only:
    - master
sudo: false
cache:
  directories:
    - vim-src
before_install:
  # Set up hg purge.
  - echo '[extensions]' > ~/.hgrc
  - echo 'purge =' >> ~/.hgrc
install: |
  if [ ! -d $TRAVIS_BUILD_DIR/vim-src/.hg ]; then
    hg clone https://code.google.com/p/vim $TRAVIS_BUILD_DIR/vim-src
  else
    hg pull -u -R $TRAVIS_BUILD_DIR/vim-src
  fi
before_script:
  - find $TRAVIS_BUILD_DIR/patches -type f -not -path '*/\.*'
      -exec patch -p1 -d $TRAVIS_BUILD_DIR/vim-src -i {} \;
script:
  - cd $TRAVIS_BUILD_DIR/vim-src/src
  - ./configure --with-features=$FEATURES
  - make
  - ./vim --version
  - make test
  # Clean up, otherwise build results will be cached by Travis.
  - cd ..
  # Remove all files not in the repo, even the ignored ones.
  - rm .hgignore
  - hg purge
  # hg update --clean will restore .hgignore.
  - hg update --clean
